using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Corathing.Organizer.Database.Model.Identity;

public class IdentityUserTokenEntity : IdentityUserToken<string>
{
    // --------------------------------------------------------------------
    // 테이블에 정의되는 속성들
    // --------------------------------------------------------------------
    // Generated by inherited IdentityUserToken
    // <code> public required string UserId { get; set; } </code>
    // <code> public string? Value { get; set; } </code>

    public string? RefreshToken { get; set; }

    public override string LoginProvider { get; set; } = "CoraIdentity";

    public override string Name { get; set; } = "CoraToken";

    public string TokenType { get; set; } = "Bearer";

    public bool CanExpire { get; set; } = true;

    public DateTime? CreatedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }


    // --------------------------------------------------------------------
    // 런타임에 참조되거나 매핑되는 속성들
    // --------------------------------------------------------------------
    public virtual IdentityUserEntity? User { get; set; }

    public static void BuildSqlLite(EntityTypeBuilder<IdentityUserTokenEntity> builder)
    {
        builder.Property(t => t.CreatedAt)
               .HasDefaultValueSql("DATETIME('now')")
               .ValueGeneratedOnAdd();

        builder.HasOne(t => t.User)
               .WithMany(u => u.UserTokens)
               .HasForeignKey(t => t.UserId)
               .IsRequired();
    }
}

