//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corathing.Organizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CorathingOrganizerLocalizationStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorathingOrganizerLocalizationStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corathing.Organizer.Resources.CorathingOrganizerLocalizationStringResources", typeof(CorathingOrganizerLocalizationStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_AppLanguage {
            get {
                return ResourceManager.GetString("Corathing.Organizer.AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_AppLanguageDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.AppLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_AppTheme {
            get {
                return ResourceManager.GetString("Corathing.Organizer.AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_AppThemeDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.AppThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_CurrentConfigureFile {
            get {
                return ResourceManager.GetString("Corathing.Organizer.CurrentConfigureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_CurrentConfigureFileDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.CurrentConfigureFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_Dark {
            get {
                return ResourceManager.GetString("Corathing.Organizer.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_Light {
            get {
                return ResourceManager.GetString("Corathing.Organizer.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_ManageCorathingAppConfigurationFile {
            get {
                return ResourceManager.GetString("Corathing.Organizer.ManageCorathingAppConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_Settings {
            get {
                return ResourceManager.GetString("Corathing.Organizer.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_UseApplicationFolder {
            get {
                return ResourceManager.GetString("Corathing.Organizer.UseApplicationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_UseApplicationFolderDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.UseApplicationFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_UseGlobalConfigurationFolder {
            get {
                return ResourceManager.GetString("Corathing.Organizer.UseGlobalConfigurationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_UseGlobalConfigurationFolderDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.UseGlobalConfigurationFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_UseUserCustomFile {
            get {
                return ResourceManager.GetString("Corathing.Organizer.UseUserCustomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_UseUserCustomFolderDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.UseUserCustomFolderDescription", resourceCulture);
            }
        }
    }
}
