//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corathing.Widgets.Basics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BasicWidgetStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasicWidgetStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corathing.Widgets.Basics.Resources.BasicWidgetStringResources", typeof(BasicWidgetStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_CalendarName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.CalendarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_CommanderName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.CommanderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_FileOpenerName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.FileOpenerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_Files_OptionTypeFile {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.Files.OptionTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_Files_OptionTypeFolder {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.Files.OptionTypeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_Files_OptionTypeTitle {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.Files.OptionTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_LinkOpenerName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.LinkOpenerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_NoteName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.NoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_TextEditorName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.TextEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_TimerName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.TimerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_ToDoListName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.ToDoListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_WebPageName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.WebPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Widgets_Basics_WebQueryName {
            get {
                return ResourceManager.GetString("Corathing.Widgets.Basics.WebQueryName", resourceCulture);
            }
        }
    }
}
