//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corathing.Organizer.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CorathingOrganizerLocalizationStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorathingOrganizerLocalizationStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corathing.Organizer.WPF.Resources.CorathingOrganizerLocalizationStringResources", typeof(CorathingOrganizerLocalizationStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_AppLanguage {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_AppLanguageDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.AppLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_AppTheme {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_AppThemeDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.AppThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_CurrentConfigureFile {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.CurrentConfigureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_CurrentConfigureFileDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.CurrentConfigureFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_Dark {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_Light {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_ManageCorathingAppConfigurationFile {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.ManageCorathingAppConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_Settings {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_UseApplicationFolder {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.UseApplicationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_UseApplicationFolderDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.UseApplicationFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_UseGlobalConfigurationFolder {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.UseGlobalConfigurationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_UseGlobalConfigurationFolderDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.UseGlobalConfigurationFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_UseUserCustomFile {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.UseUserCustomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Corathing_Organizer_WPF_UseUserCustomFolderDescription {
            get {
                return ResourceManager.GetString("Corathing.Organizer.WPF.UseUserCustomFolderDescription", resourceCulture);
            }
        }
    }
}
